model_name: "two_stream_salient"

preprocess:
  sequence_epochs: 20
  big_group_size: 100
  enhance_window_stride: 2

train:
  batch_size: 32
  epochs: 100
  filters: [16, 32, 64, 128, 256]
  kernel_size: 3
  pooling_sizes: [10, 8, 6, 4]
  dilation_sizes: [1, 2, 4, 8]
  activation: "relu"
  u_depths: [4, 4, 4, 4, 4]
  u_inner_filter: 32
  mse_filters: [8, 16, 32, 64, 128]
  optimizer: "adam"
  learning_rate: 0.001
  padding: "same"

evaluation:
  label_class: ["W", "N1", "N2", "N3", "REM"]

class_weights: [1.0, 1.80, 1.0, 1.25, 1.20]
patience: 5
sleep_epoch_len: 3000
num_classes: 5

# 添加分布式训练参数
distributed:
  enable: true  # 是否启用分布式训练
  strategy: "mirrored"  # 分布式策略: "mirrored" 或 "multi_worker"